/* enums for the following
 * BlockchainType
 * ErcType
 * SaleType
 * CollectibleCategory
 * ProductKeyVirtualAssetCategory
 * ProductKeyAccessTokenCategory
 */

export enum BlockchainType {
  POLYGON = 'POLYGON',
}

export enum ErcType {
  ERC_721 = 'ERC_721',
  ERC_1155 = 'ERC_1155',
}

export enum SaleType {
  COLLECTIBLE = 'COLLECTIBLE',
  PRODUCT_KEY_REAL_LIFE_ASSET = 'PRODUCT_KEY_REAL_LIFE_ASSET',
  PRODUCT_KEY_VIRTUAL_ASSET = 'PRODUCT_KEY_VIRTUAL_ASSET',
}

export enum CollectibleCategory {
  MISCELLANEOUS = 'MISCELLANEOUS',
  EXCLUSIVE = 'EXCLUSIVE',
  ABSTRACT = 'ABSTRACT',
  PIXEL = 'PIXEL',
  CARTOON = 'CARTOON',
  CLASSIC = 'CLASSIC',
  COMPUTER_GRAPHIC = 'COMPUTER_GRAPHIC',
  VIDEO_GAME = 'VIDEO_GAME',
  SCENERY = 'SCENERY',
  PERFORMANCE = 'PERFORMANCE',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  ACHITECTURE = 'ACHITECTURE',
  MUSIC = 'MUSIC',
  MEME = 'MEME',
  DOMAIN_NAME = 'DOMAIN_NAME',
  SPORTS_CARD = 'SPORTS_CARD',
  TRADING_CARD = 'TRADING_CARD',
}

export enum ProductKeyAccessTokenCategory {
  MISCELLANEOUS = 'MISCELLANEOUS',
  // Soon to be added
}

export enum ProductKeyVirtualAssetCategory {
  MISCELLANEOUS = 'MISCELLANEOUS',
  CLOTHING_WEARABLE = 'CLOTHING_WEARABLE',
  BEAUTY_ACCESSORY = 'BEAUTY_ACCESSORY',
  TOOL_EQUIPMENT = 'TOOL_EQUIPMENT',
  MATERIAL_MACHINE_PART = 'MATERIAL_MACHINE_PART',
  ELECTRONIC_APPLIANCE = 'ELECTRONIC_APPLIANCE',
  GROCERY_FOOD = 'GROCERY_FOOD',
  WEAPON = 'WEAPON',
  FURNITURE = 'FURNITURE',
  REAL_ESTATE = 'REAL_ESTATE',
  TOY_GAME = 'TOY_GAME',
  HOME_SUPPLY = 'HOME_SUPPLY',
  MEDICAL_MAGIC_ITEM = 'MEDICAL_MAGIC_ITEM',
}
